# Filterbank config
filterbank:
  n_filters: 512
  kernel_size: 16
  stride: 8
# Network config
masknet:
  n_blocks: 8
  n_repeats: 3
  mask_act: relu
  bn_chan: 128
  skip_chan: 128
  hid_chan: 512
# Training config
training:
  epochs: 200
  batch_size: 1
  num_workers: 1
  half_lr: yes
  early_stop: yes
# Optim config
optim:
  optimizer: adam
  lr: 0.001
  weight_decay: 0.
# Data config
data:
  train_dir: data/convtasnet/data/wav8k/eng_eat_tai_100/tr/
  valid_dir: data/convtasnet/data/wav8k/eng_eat_tai_100/cv/
  task: sep_noisy
  nondefault_nsrc:
  sample_rate: 8000
  mode: min
